# Generated by Django 4.2.23 on 2026-07-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video_processor", "0006_alter_videojob_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="videojob",
            name="file_removed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the media file was deleted to reclaim storage",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="videojob",
            index=models.Index(
                fields=["user", "status"], name="video_proce_user_id_1e37ca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="videojob",
            index=models.Index(
                fields=["user", "created_at"], name="video_proce_user_id_8e6a8a_idx"
            ),
        ),
    ]
